apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-microservice
  labels:
    app: java-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-microservice
  template:
    metadata:
      labels:
        app: java-microservice
    spec:
      containers:
        - name: java-microservice
          image: my-java-app:latest   # <-- replace with your image, e.g., your-dockerhub-user/my-java-app:1.0
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: java-microservice
spec:
  selector:
    app: java-microservice
  ports:
    - protocol: TCP
      port: 8080        # Service port
      targetPort: 8080  # Container port
      nodePort: 30080   # Exposed port on each node (change if needed)
  type: NodePort
